"""empty message

Revision ID: 47808190cf43
Revises: 2085daeaa09a
Create Date: 2019-12-09 00:23:52.509528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47808190cf43'
down_revision = '2085daeaa09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###
