"""empty message

Revision ID: 576e5f4a0fe7
Revises: e3394819e31e
Create Date: 2019-11-26 23:54:27.340518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576e5f4a0fe7'
down_revision = 'e3394819e31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('web_site', sa.String(length=120), nullable=True))

    op.execute('UPDATE venues SET seeking_talent = False;')
    op.alter_column('venues', 'seeking_talent', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'web_site')
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'seeking_description')
    # ### end Alembic commands ###
