"""empty message

Revision ID: f9936d0a6f36
Revises: 47808190cf43
Create Date: 2019-12-10 20:16:58.010485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9936d0a6f36'
down_revision = '47808190cf43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('venues', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('artists', 'name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
